services:
  web:
    build: .
    ports:
      - "5001:8080"  # Host:Container port mapping
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Port=3306;Database=ProjectDashboardDB;User=root;
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=ProjectDashboardDB
    volumes:
      - mysql_data:/var/lib/mysql  # This references the volume
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10

volumes:  # THIS SECTION WAS MISSING
  mysql_data:  # Declares the volume