services:
  # Application Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_app
    ports:
      - "8080:80" # Map port 8080 on host to port 80 in the container
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=ProjectDashboardDB
    volumes:
      - .:/var/www/html # Mount your local code into the container
    depends_on:
      - db

  # Database Service (MySQL)
  db:
    image: mysql:8.0
    container_name: my_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: ProjectDashboardDB
      MYSQL_USER: root
      MYSQL_PASSWORD:
    ports:
      - "3306:3306" # Expose MySQL port
    volumes:
      - db_data:/var/lib/mysql # Persist MySQL data

  # phpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: my_phpmyadmin
    restart: always
    ports:
      - "8081:80" # Access phpMyAdmin at http://localhost:8081
    environment:
      PMA_HOST: db # The hostname of the database service
      MYSQL_ROOT_PASSWORD:
    depends_on:
      - db

volumes:
  db_data: # Persistent volume for MySQL data

#   "ConnectionStrings": {
#   "DefaultConnection": "Server=db;Port=3306;Database=ProjectDashboardDB;User=root;Password=;"
# }
